version: "3.7"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: .
    env_file:
      - .env.local
    ports:
      - "8000:3000"
    depends_on:
      - database
    networks:
      - backend

networks:
  backend:
    driver: bridge